config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
  registrations: 'users/registrations',
  sessions: 'users/sessions',
  omniauth_callbacks: "users/omniauth_callbacks"
  }
  
  devise_scope :user do
    get 'expert_secondcategory' => 'users/registrations#expert_secondcategory'
    get 'expert_thirdcategory'  => 'users/registrations#expert_thirdcategory'
  end


  root 'items#index'

  resources :items do
    resources :communications,only:[:create]
    member do
      post 'pay'
    end
    resources :likes, only: [:create, :destroy]
    resources :flags, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update] do
    resources :payment_informations, only: [:index, :new, :create, :destroy]
  end

  resources :orders, only: [:show, :create]

  match 'secondcategory', to: 'items#secondcategory', via: [:get, :post]
  match 'thirdcategory', to: 'items#thirdcategory', via: [:get, :post]
  match 'search_secondcategory', to: 'items#search_secondcategory', via: [:get, :post]
  match 'search_thirdcategory', to: 'items#search_thirdcategory', via: [:get, :post]
  resources :categorys
  resources :second_categorys, only: [:show]
  resources :third_categorys, only: [:show]
  resources :brands, only: [:show]
  get "logout", to: 'users#logout'
  get "users-form", to: 'users#index'
  get "search", to: 'items#search', as: 'search'
  get "order_confirm/:id", to: 'items#order_confirm', as: 'order_confirm'
  get "users/user_info/:id", to: 'users#user_info', as: 'users_user_info'
  get "users/user_exhibitation_products/:id", to: 'users#user_exhibitation_products', as: 'user_exhibitation_products'
  get "users/user_item_show/:id", to: 'users#user_item_show', as: 'user_item_show'
  get "order_status/:id", to: 'items#order_status', as: 'order_status'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable,omniauth_providers: [:facebook, :google_oauth2]
  validates :nickname,:first_name,:first_name_kana,:last_name,:last_name_kana,:city,:address,:zip_code,:telephone,:birth_year,:birth_month,:birth_day,presence: true
  validates :zip_code,length: { maximum:7 }
  validates :telephone ,numericality:true
  has_many   :items, dependent: :destroy
  has_many   :orders, dependent: :destroy
  has_many   :profits, dependent: :destroy
  has_many   :points, dependent: :destroy
  has_many   :communications, dependent: :destroy
  has_many   :likes, dependent: :destroy
  has_many   :flags, dependent: :destroy
  has_many   :rate_counts, dependent: :destroy
  has_many   :message_items,    through: :communications, source: :item, dependent: :destroy
  has_many   :like_items,       through: :likes,          source: :item, dependent: :destroy
  has_many   :flag_items,       through: :flags,          source: :item, dependent: :destroy
  has_many   :rating_items,     through: :rate_counts,     source: :item, dependent: :destroy
  has_many   :sns_credentials, dependent: :destroy

  has_many   :payment_information, dependent: :destroy
  belongs_to :prefecture, optional: true
  belongs_to :first_category, optional: true
  belongs_to :second_category, optional: true
  belongs_to :third_category, optional: true

  # def self.find_oauth(auth)
  #   uid = auth.uid
  #   provider = auth.provider
  #   snscredential = SnsCredential.where(uid: uid, provider: provider).first
  #   if snscredential.present?
  #     user = User.where(id: snscredential.user_id).first
  #   else
  #     user = User.where(email: auth.info.email).first
  #     if user.present?
  #       SnsCredential.create(
  #         uid: uid,
  #         provider: provider,
  #         user_id: user.id
  #         )
  #     else
  #       user = User.create(
  #         nickname: auth.info.name,
  #         email:    auth.info.email,
  #         password: Devise.friendly_token[0, 20],
  #         telephone: "08000000000"
  #         )
  #       SnsCredential.create(
  #         uid: uid,
  #         provider: provider,
  #         user_id: user.id
  #         )
  #     end
  #   end
  #   return user
  # end
  def self.find_oauth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.where(uid: uid, provider: provider).first
    # binding.pry

    if snscredential.present? #sns登録のみ完了してるユーザー
      user = User.where(id: snscredential.user_id).first
      unless user.present? #ユーザーが存在しないなら
        user = User.new(
          # snsの情報
          # binding.pry => auth.infoとかで確認 
          nickname: auth.info.name,
          email: auth.info.email
        )
      end
      sns = snscredential
      #binding.pry

    else #sns登録 未
      user = User.where(email: auth.info.email).first
      if user.present? #会員登録 済
        sns = SnsCredential.new(
          uid: uid,
          provider: provider,
          user_id: user.id
        )
      else #会員登録 未
        user = User.new(
          nickname: auth.info.name,
          email: auth.info.email
        )
        # binding.pry
        sns = SnsCredential.create(
          uid: uid,
          provider: provider
        )
        # binding.pry 
      end
    end
    # binding.pry
    # hashでsnsのidを返り値として保持しておく
    return { user: user , sns_id: sns.id }
  end

  def already_liked?(item)
    self.likes.exists?(item_id: item.id)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_for(:facebook) #コールバック
  end

  def google_oauth2
    callback_for(:google) #コールバック
  end

  def callback_for(provider)
    info = User.find_oauth(request.env["omniauth.auth"]) #usersモデルのメソッド
    @user = info[:user]
    sns_id = info[:sns_id]
    # binding.pry
    if @user.persisted? #userが存在したら
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else #userが存在しなかったら
      session["devise.sns_id"] = sns_id #sns_credentialのid devise.他のアクションに持ち越せる(少し難)
      render template: "devise/registrations/new"#redirect_to だと更新してしまうのでrenderで
    end
  end

  def failure
    redirect_to root_path and return
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  # before_action :check_recaptcha, only: %i(create)

  def new
    super
  end
  
  def expert_secondcategory
    @secondcategory = SecondCategory.where(first_category_id: params[:user][:first_category_id])
  end

  def expert_thirdcategory
    @thirdcategory = ThirdCategory.where(second_category_id: params[:user][:second_category_id])
  end
  # def create
  #   super
  # end

  def create
    #binding.pry
    if params[:user][:password] == "" #sns登録なら
      params[:user][:password] = "Devise.friendly_token.first(6)" #deviseのパスワード自動生成機能を使用
      params[:user][:password_confirmation] = "Devise.friendly_token.first(6)"
      super
      # binding.pry
      sns = SnsCredential.update(user_id:  @user.id)
    else #email登録なら
      # binding.pry
      super
    end
  end

  private
  def check_recaptcha
    unless verify_recaptcha
      self.resource = resource_class.new sign_up_params
      resource.validate
      respond_with_navigational(resource) { render :new }
    end
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :check_recaptcha, only: %i(create)

  # def create
  #   super
  # end

  # protected
  # def check_recaptcha
  #   unless verify_recaptcha
  #     self.resource = resource_class.new sign_in_params
  #     resource.validate
  #     respond_with_navigational(resource) { render :new }
  #   end
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :move_to_index, except: [:index]

  def index
  end

  def show
  end

  def edit
  end

  def user_info
  end

  def update
    if current_user.update(user_params)
      redirect_to user_path(current_user.id)
    else
      redirect_to user_path(current_user.id)
    end
  end

  def user_exhibitation_products
    @items = Item.where(user_id: current_user.id)
  end

  def user_item_show
    @item = Item.find(params[:id])
    @item_images = @item.item_images
  end

  def delete
  end

  def move_to_index
    redirect_to root_path unless user_signed_in?
  end

  private
  def user_params
    params.require(:user).permit(
      :nickname, :first_name, :first_name_kana, :last_name, :last_name_kana, :city, :address, :building, :email, :encrypted_password, :reset_password_token, :telephone, :zip_code, :birth_year, :birth_month, :birth_day, :point_amount, :profit_amount, :user_icon, :introduction, :remember_created_at, :reset_password_sent_at, :created_at, :updated_at, :prefecture_id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def converting_zip_code(code)
    "〒#{code.to_s.insert(3, '-')}"
  end
end

app/views/users/_large-content.html.haml
%section.mypage-user-icon
  = link_to do
    %figure
      = image_tag "header-footer_images/member_photo.png", size:"60x60", class: "user-icon"
    %h2.bold
      = current_user.nickname
    .mypage-number
      %div
        評価
        %span.bold
          0
      %div
        出品数
        %span.bold
%section.mypage-tab-container#mypage-notification-todo
  %ul.mypage-tabs
    %li.mypage-tab#tab-notification.active
      %h3
        %p
          お知らせ
    %li.mypage-tab#tab-todo
      %h3
        %p
          やることリスト
  .tab-content
    %ul#mypage-tab-notification.mypage-item-list.tab-pane.active
      %li.mypage-item-not-found.not-found-bold
        お知らせがありません
    %ul#mypage-tab-todos.mypage-item-list.tab-pane.not-active
      %li.mypage-item-not-found.not-found-bold
        現在、やることリストはありません
%section.mypage-tab-container#mypage-transaction-now-old
  .mypage-tab-head
    購入した商品
  %ul.mypage-tabs
    %li.mypage-tab.active#tab-transaction-now
      %h3
        %p
          取引中
    %li.mypage-tab#tab-transaction-old
      %h3
        %p
          過去の取引
  .tab-content
    %ul#mypage-tab-transaction-now.mypage-item-list.tab-pane.active
      %li.mypage-item-not-found.not-found-bold
        取引中の商品がありません
    %ul#mypage-tab-transaction-old.mypage-item-list.tab-pane.not-active
      %li.mypage-item-not-found.not-found-bold
        過去に取引した商品がありません

app/views/users/_mypage-left-side.html.haml
.left-side_box
  %nav.mypage-nav
    %ul.mypage-nav__list
      %li
        =link_to user_path(current_user), class: "mypage-nav__list__item" do
          マイページ
          = fa_icon "angle-right"
      %li
        =link_to "#", class: "mypage-nav__list__item" do
          お知らせ
          = fa_icon "angle-right"
      %li
        =link_to "#", class: "mypage-nav__list__item" do
          やることリスト
          = fa_icon "angle-right"
      %li
        =link_to "#", class: "mypage-nav__list__item" do
          いいね！一覧
          = fa_icon "angle-right"
      %li
        =link_to new_item_path, class: "mypage-nav__list__item" do
          出品する
          = fa_icon "angle-right"
      %li
        =link_to user_exhibitation_products_path(current_user.id), class: "mypage-nav__list__item" do
          出品した商品-出品中
          = fa_icon "angle-right"
      %li
        =link_to "#", class: "mypage-nav__list__item" do
          出品した商品-取引中
          = fa_icon "angle-right"
      %li
        =link_to "#", class: "mypage-nav__list__item" do
          出品した商品-売却済み
          = fa_icon "angle-right"
      %li
        =link_to "#", class: "mypage-nav__list__item" do
          購入した商品-取引中
          = fa_icon "angle-right"
      %li
        =link_to "#", class: "mypage-nav__list__item" do
          購入した商品-過去の取引
          = fa_icon "angle-right"
      %li
        =link_to "#", class: "mypage-nav__list__item" do
          ニュース一覧
          = fa_icon "angle-right"
      %li
        =link_to "#", class: "mypage-nav__list__item" do
          評価一覧
          = fa_icon "angle-right"
      %li
        =link_to "#", class: "mypage-nav__list__item" do
          ガイド
          = fa_icon "angle-right"
      %li
        =link_to "#", class: "mypage-nav__list__item" do
          お問い合わせ
          = fa_icon "angle-right"
    %h3.mypage-nav__head
      売上・ポイント
    %ul.mypage-nav__list
      %li
        =link_to "#", class: "mypage-nav__list__item" do
          売上・振込申請
          = fa_icon "angle-right"
      %li
        =link_to "#", class: "mypage-nav__list__item" do
          ポイント
          = fa_icon "angle-right"
    %h3.mypage-nav__head
      設定
    %ul.mypage-nav__list
      %li
        =link_to edit_user_path(current_user.id), class: "mypage-nav__list__item" do
          プロフィール
          = fa_icon "angle-right"
      %li
        =link_to "#", class: "mypage-nav__list__item" do
          住所変更
          = fa_icon "angle-right"
      %li
        =link_to user_payment_informations_path(current_user), class: "mypage-nav__list__item" do
          支払い方法
          = fa_icon "angle-right"
      %li
        =link_to "#", class: "mypage-nav__list__item" do
          メール/パスワード
          = fa_icon "angle-right"
      %li
        =link_to users_user_info_path(current_user.id), class: "mypage-nav__list__item" do
          本人情報
          = fa_icon "angle-right"
      %li
        =link_to "#", class: "mypage-nav__list__item" do
          電話番号の確認
          = fa_icon "angle-right"
      %li
        =link_to logout_path, class: "mypage-nav__list__item" do
          ログアウト
          = fa_icon "angle-right"

app/views/users/edit.html.haml
= render partial: "items/header"
.breads
  - breadcrumb :profile
  = breadcrumbs separator: "#{content_tag(:i, '', class: 'fa fa-caret-right')}"
.default-container
  %main.large-container.clearfix
    = form_for(current_user) do |f|
      .edit-profile-box
        .edit-profile-box__head
          プロフィール
        .edit-profile-box__user-info
          .edit-profile-box__user-info__box
            .edit-profile-box__user-info__box__icon
              - if current_user.user_icon.present?
                = image_tag current_user.user_icon
              - else
                = image_tag "header-footer_images/member_photo.png"
            = f.text_field :nickname, placeholder: "名前を入力", color: "black"
        .edit-profile-box__message
          = f.text_area :introduction, placeholder: "例）こんにちは☆ ご覧いただきありがとうございます！かわいいものやきれいめオフィスカジュアル中心に出品しています。服のサイズは主に9号です。気持ちよくお取引できるよう心がけていますので、商品や発送方法などご質問がありましたらお気軽にどうぞ♪", color: "black"
          = f.submit "変更する", class: "edit-profile-box__update-btn"
    = render partial: "mypage-left-side"
= render partial: "items/footer"

app/views/users/index.html.haml
.single-container
  = render 'devise/shared/header'
  %main.single-main
    %section.l-single-container
      %h2.l-single-head
        新規会員登録
      .l-single-inner
        .l-single-content
          = link_to new_user_registration_path, class: "btn-default btn-mail" do
            = fa_icon "envelope", class: "icon-mail", type: :far
            メールアドレスで登録
          = link_to user_facebook_omniauth_authorize_path, id: "facebook-login", class: "btn-default btn-sns btn-sns-facebook" do
            = fa_icon "facebook", class: "icon-facebook", type: :fab
            Facebookで登録
          = link_to user_google_oauth2_omniauth_authorize_path, id: "google-login", class: "btn-default btn-sns btn-sns-google" do
            = fa_icon "google", class: "icon-google", type: :fab
            Googleで登録
  = render 'devise/shared/footer'

app/views/users/logout.html.haml
= render partial: "items/header"
.breads
  - breadcrumb :logout
  = breadcrumbs separator: "#{content_tag(:i, '', class: 'fa fa-angle-right')}"
.default-container
  %main.large-container.clearfix
    .large-content
      .logout-box
        .logout-box__btn
          = link_to "ログアウト", destroy_user_session_path, method: :delete,class:"logout-btn"
    = render partial: "mypage-left-side"
= render partial: "items/footer"

app/views/users/show.html.haml
= render partial: "items/header"
.breads
  - breadcrumb :mypage
  = breadcrumbs separator: "#{content_tag(:i, '', class: 'fa fa-angle-right')}"
.default-container
  %main.large-container.clearfix
    .large-content
      =render partial: "large-content"
    =render partial: "mypage-left-side"
= render partial: "items/footer"

app/views/users/user_exhibitation_products.html.haml
= render partial: "items/header"
.breads
  - breadcrumb :exhibit_items
  = breadcrumbs separator: "#{content_tag(:i, '', class: 'fa fa-angle-right')}"
.default-container
  %main.large-container.clearfix
    .large-content2
      =render partial: "users/user_exhibitation_products_folder/main_content_exhibitation"
    =render partial: "mypage-left-side"
= render partial: "items/footer"

app/views/users/user_info.html.haml
= render partial: "items/header"
.breads
  - breadcrumb :user_info
  = breadcrumbs separator: "#{content_tag(:i, '', class: 'fa fa-angle-right')}"
.default-container
  %main.large-container.clearfix
    .large-content
      %section.l-chapter-container
        %h2.l-chapter-head
          本人情報の登録
        %p.text-center
          お客さまのあんしん・あんぜんな取引のため、本人情報のご登録をお願いしております。
        .l-single-inner
          = form_for(current_user) do |f|
            .address-info
              .info-head
                住所
              %span
                必須
              .address-text
                %p
                  #{converting_zip_code(current_user.zip_code)}
                %p
                  #{current_user.prefecture.prefecture}#{current_user.city}#{current_user.address}
                %p
                  #{current_user.first_name}#{current_user.last_name}
                = link_to "編集"
            .birth-info
              .info-head
                生年月日
              %span
                必須
              .birth-select-wrap
                .select-wrap
                  .select-box
                    = f.select :birth_year,[*(1900..2018)]
                %p
                  年
                .select-wrap
                  .select-box
                    = f.select :birth_month,[*(1..12)]
                %p
                  月
                .select-wrap
                  .select-box
                    = f.select :birth_day,[*(1..31)]
                %p
                  日
            .form-info-text
              %p
                ※出品されたことがある、本人情報未登録のお客さまもご対象となります。
            .update-box
              = f.submit "登録する", class:"update-box-btn"
            .info-text-right
              %p
                = link_to "本人情報の登録について＞"
    = render partial: "mypage-left-side"
= render partial: "items/footer"

app/views/users/user_item_show.html.haml
= render partial: "items/header"
.breads
  - breadcrumb :exhibit_item
  = breadcrumbs separator: "#{content_tag(:i, '', class: 'fa fa-angle-right')}"
.default-container
  %section.item-container
    %h1 #{@item.name}
    .item-container__main-content
    .item-container__image
      = image_tag  "#{@item_images[0]&.image}", alt: "", id: "main-box"
      - if @item.order_status_id == 3
        .sell-stop-box
          .sell-stop-text STOP
      %ul.image-slide
        %li
        - @item_images.each do|item|
          %li
            =image_tag "#{item.image}",alt:"", class: "slide-box"
            
    %table.item-container__detail
      %tbody
        %tr
          %th 出品者
          %td
            = link_to "#{@item.user.nickname}"
        %tr
          %th カテゴリー
          %td
            = link_to "#{@item.first_category.first_category}"
            %br
            = link_to "\→#{@item.second_category.second_category}"
            %br
            = link_to "\→#{@item.third_category.third_category}"
        %tr
          %th ブランド
          %td #{@item.brand.brand}
        %tr
          %th 商品のサイズ
          %td #{@item.size.size}
        %tr
          %th 商品の状態
          %td #{@item.condition.condition}
        %tr
          %th 配送料の負担
          %td #{@item.delivery_charge.charge}
        %tr
          %th 配送の方法
          %td #{@item.delivery_way.way}
        %tr
          %th 配送元地域
          %td
            = link_to "#{@item.prefecture.prefecture}"
        %tr
          %th 発送日の目安
          %td #{@item.delivery_date.date}
    .item-container__price
      %span.item-price
        = number_to_currency(@item.price, format:"%u%n", unit: "￥", strip_insignificant_zeros: true)
      %span.item-taxIn
        (税込)
      %span.item-tax-include
        \送料込み
    .item-container__discription
      %p
      \#{@item.description}
  .listing-item-change-box
    = link_to edit_item_path(@item), class: "item-info-red" do
      商品の編集
    %p 
      or
    - if @item.order_status.id == 1
      = link_to order_status_path(@item), class: "item-info-gray" do
        出品を停止する
    - else
      = link_to order_status_path(@item), class: "item-info-red" do
        出品を再開する
        
    = link_to "この商品を削除する", item_path, method: :delete, data: { confirm: '確認削除すると二度と復活できません。削除する代わりに停止することもできます。本当に削除しますか？' }, class: "item-info-gray"
  .comment
    .comment__box
      %p相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
      .form
      .send コメントする
= render partial: "items/footer"