config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
  registrations: 'users/registrations',
  sessions: 'users/sessions',
  omniauth_callbacks: "users/omniauth_callbacks"
  }
  
  devise_scope :user do
    get 'expert_secondcategory' => 'users/registrations#expert_secondcategory'
    get 'expert_thirdcategory'  => 'users/registrations#expert_thirdcategory'
  end


  root 'items#index'

  resources :items do
    resources :communications,only:[:create]
    member do
      post 'pay'
    end
    resources :likes, only: [:create, :destroy]
    resources :flags, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update] do
    resources :payment_informations, only: [:index, :new, :create, :destroy]
  end

  resources :orders, only: [:show, :create]

  match 'secondcategory', to: 'items#secondcategory', via: [:get, :post]
  match 'thirdcategory', to: 'items#thirdcategory', via: [:get, :post]
  match 'search_secondcategory', to: 'items#search_secondcategory', via: [:get, :post]
  match 'search_thirdcategory', to: 'items#search_thirdcategory', via: [:get, :post]
  resources :categorys
  resources :second_categorys, only: [:show]
  resources :third_categorys, only: [:show]
  resources :brands, only: [:show]
  get "logout", to: 'users#logout'
  get "users-form", to: 'users#index'
  get "search", to: 'items#search', as: 'search'
  get "order_confirm/:id", to: 'items#order_confirm', as: 'order_confirm'
  get "users/user_info/:id", to: 'users#user_info', as: 'users_user_info'
  get "users/user_exhibitation_products/:id", to: 'users#user_exhibitation_products', as: 'user_exhibitation_products'
  get "users/user_item_show/:id", to: 'users#user_item_show', as: 'user_item_show'
  get "order_status/:id", to: 'items#order_status', as: 'order_status'
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :item_images, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :flags, dependent: :destroy
  has_many :message_users,through: :messages,source: :user
  has_many :like_users,through: :likes,source: :user
  has_many :flag_users,through: :flags,source: :user
  has_many :communications

  belongs_to :order, optional: true
  belongs_to :profit, optional: true
  belongs_to :prefecture, optional: true
  belongs_to :user, optional: true
  belongs_to :first_category, optional: true
  belongs_to :second_category, optional: true
  belongs_to :third_category, optional: true
  belongs_to :brand, optional: true
  belongs_to :condition, optional: true
  belongs_to :delivery_charge, optional: true
  belongs_to :delivery_date, optional: true
  belongs_to :delivery_way, optional: true
  belongs_to :order_status, optional: true
  belongs_to :size, optional: true
  accepts_nested_attributes_for :item_images

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :authenticate_user!, except: [:index,:show]
  before_action :set_item, only: [:show, :edit, :update, :destroy, :order_confirm, :order_status]
  before_action :set_Category, only: [:new, :create, :edit, :update, :search]

  def index
    @items = Item.includes(:item_images).limit(4).order("created_at DESC")
  end

  def show
    @item_images = @item.item_images.where(item_id: @item.id)
    @user = current_user
    @message = Communication.new
    @like = Like.new
  end

  def new
    @item = current_user.items.new
    @item_images = 4.times{@item.item_images.build}
  end

  def create
    @item = current_user.items.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new, item_images: @item.item_images.build
    end
  end

  def edit
    (4 - @item.item_images.size).times{@item.item_images.new}
  end

  def update
    if @item.user_id == current_user.id
      if @item.update(item_params)
        redirect_to user_item_show_path(@item)
      else
        (4 - @item.item_images.size).times{@item.item_images.new}
        render :edit
      end
    end
  end


  def destroy
    if @item.user_id == current_user.id
      @item.destroy
    end
    redirect_to user_exhibitation_products_path(current_user.id)
  end

  def secondcategory
    @secondcategory = SecondCategory.where(first_category_id: params[:item][:first_category_id])
  end

  def thirdcategory
    @thirdcategory = ThirdCategory.where(second_category_id: params[:item][:second_category_id])
  end

  def search_secondcategory
    @secondcategory = SecondCategory.where(first_category_id: params[:q][:first_category_id_eq])
  end

  def search_thirdcategory
    @thirdcategory = ThirdCategory.where(second_category_id: params[:q][:second_category_id_eq])
  end

    Payjp::api_key ='sk_test_01fd21565272036e9153cfa6'

  def self.create_token(number, cvc, exp_year, exp_month)
  token = Payjp::Token.create(
      card: {
        number:    number,
        cvc:       cvc,
        exp_year:  exp_year,
        exp_month: exp_month,
      }
    )
    return token.id
  end

  def pay
    Payjp.api_key = 'sk_test_01fd21565272036e9153cfa6'
    @user = current_user
    @item = Item.find(params[:id])
    @item.update_attribute(:order_status_id, 2 )

    if customer_id = @user.customer_id
      customer = Payjp::Customer.retrieve(id: customer_id)
      charge = Payjp::Charge.create(
        amount: params['price'],
        customer: customer,
        currency: 'jpy',
      )
    else
      customer = Payjp::Customer.create(card: params['payjp-token'])
      @user.customer_id = customer.id
      @user.save

      charge = Payjp::Charge.create(
        amount: params['price'],
        customer: customer,
        currency: 'jpy',
      )
    end
    redirect_to root_path
  end

  def order_confirm
    @item_images = @item.item_images
  end

  def search
  end

  def order_status

    # 出品停止と出品中の切り替え
    if @item.order_status.id == 1
      @item.update(order_status_id: 3)
    else
      @item.update(order_status_id: 1)
    end

    redirect_back(fallback_location: root_path)
  end


  private

  def item_params
    params.require(:item).permit(
      :name, :price, :description, :first_category_id,
      :second_category_id, :third_category_id, :brand_id,
      :size_id, :condition_id, :delivery_charge_id, :prefecture_id,
      :delivery_date_id, :order_status_id, :delivery_way_id, item_images_attributes:[:id, :image, :_destroy])
  end
  
  def set_item
    @item = Item.find(params[:id])
  end

  def set_Category
    @first = FirstCategory.all
    @second = SecondCategory.all
  end
end

app/helpers/items_helper.rb
module ItemsHelper

  def converting_price(price)
   "¥#{price.to_s(:delimited, delimiter: ',')}"
  end

  def commission_jpy(commission)
   "¥#{commission.floor.to_s(:delimited, delimiter: ',')}"
  end

  def profit_jpy(profit)
   "¥#{profit.ceil.to_s(:delimited, delimiter: ',')}"
  end

end

app/views/items/_footer.html.haml
.footer-wrapper.clearfix
.footer-dl-area
  .footer-dl-area__contents
    .left-img
      %h2
        スマホでかんたんフリマアプリ
      %p
        今すぐ無料ダウンロード！
      .app-banner-icon.clearfix
        %figure.app-banner-icon__icons-box
          = image_tag("header-footer_images/mercari_icon.png", class: "mercari-icon")
        %ul.imgs
          %li
            = image_tag("header-footer_images/app-store.svg", class: "imgs__store app")
          %li
            = image_tag("header-footer_images/google-play.svg", class: "imgs__store google")
    .right-img
      = image_tag("header-footer_images/download_content_pc.png", class: "download_content_pc")
.fotter
  %nav
    %ul
      %li.fotter-cell.about-mercari
        %h2.fotter__header
          メルカリについて
        %ul
          %li
            = link_to "" do
              会社概要（運営会社）
          %li
            = link_to "" do
              プライバシーポリシー
          %li
            = link_to "" do
              メルカリ利用規約
          %li
            = link_to "" do
              メルカリ利用規約・有償ポイントに関する特約
          %li
            = link_to "" do
              あんしんスマホサポート制度に関する利用特約
          %li
            = link_to "" do
              コンプライアンスポリシー
          %li
            = link_to "" do
              個人データの安全管理に係る基本方針
          %li
            = link_to "" do
              特定商取引に関する表記
          %li
            = link_to "" do
              資金決済法に基づく表示
          %li
            = link_to "" do
              法令順守と犯罪抑止のために
          %li
            = link_to "" do
              採用情報

      %li.fotter-cell.look-at-mercari
        %h2.fotter__header
          メルカリを見る
        %ul
          %li
            = link_to "" do
              カテゴリー一覧
          %li
            = link_to "" do
              ブランド一覧
          %li
            = link_to "" do
              出品地域一覧
          %li
            = link_to "" do
              公式ブログ
          %li
            = link_to "" do
              公式Twitter
          %li
            = link_to "" do
              公式Facebook

      %li.fotter-cell.help-and-guid
        %h2.fotter__header
          ヘルプ＆ガイド
        %ul
          %li
            = link_to "" do
              メルカリガイド
          %li
            = link_to "" do
              メルカリロゴ利用ガイドライン
          %li
            = link_to "" do
              お知らせ
          %li
            = link_to "" do
              らくらくメルカリ便とは
          %li
            = link_to "" do
              ゆうゆうメルカリ便とは
          %li
            = link_to "" do
              大型らくらくメルカリ便とは
          %li
            = link_to "" do
              車体取引ガイド
          %li
            = link_to "" do
              返品・返金ポリシー
          %li
            = link_to "" do
              メルカリあんしん・あんぜん宣言！
          %li
            = link_to "" do
              偽ブランド品撲滅への取り組み
          %li
            = link_to "" do
              メルカリボックス
      %li.fotter-cell.country
        %h2.fotter__header
          国
        %ul
          %li
            = link_to "" do
              United Kingdom
          %li
            = link_to "" do
              日本
  = link_to "", class: "fotter__icon" do
    =image_tag("header-footer_images/mercari-white_logo.svg")
  %p.fotter__copyright © 2019 Mercari
.exhibit
  =link_to new_item_path do
    .text
      出品
    %i.fa.fa-camera

app/views/items/_header.html.haml
.header-wrap
  %header
    .logo-and-search.clearfix
      =link_to root_path do
        = image_tag("header-footer_images/mercari-coloful_logo.svg", class: "logo-and-search__logo left-float")
      .search
        = search_form_for @search, url: search_path do |f|
          .logo-and-search__search.right-float
            = f.search_field :name_cont, placeholder:"キーワードから探す"
            = button_tag type:"submit" do
              %i.fa.fa-search
        %end
    .lists.clearfix
      %ul.gnav
        %li.left_btn1
          %h2
          = link_to categorys_path do
            カテゴリから検索
            %ul
              -FirstCategory.all.each do |firstcategory|
                %li
                  = link_to category_path(firstcategory.id), action: :show do
                    #{firstcategory.first_category}
                  %ul
                    -SecondCategory.where(first_category_id: [firstcategory.id]).each do |secondcategory|
                      %li
                        = link_to second_category_path(secondcategory.id) do 
                          #{secondcategory.second_category}
                        %ul
                          -ThirdCategory.where(second_category_id: [secondcategory.id]).each do |thirdcategory|
                            %li
                              = link_to third_category_path(thirdcategory.id) do 
                                #{thirdcategory.third_category}
                          %end
                    %end
              %end
        %li.left_btn2
          %h2
          = link_to do
            ブランドから探す
            %ul
              -Brand.all.each do |brand|
                %li
                  = link_to brand_path(brand.id), action: :show do
                    #{brand.brand}
              %end
        .space
        .lists__right.right-float
          -if user_signed_in?
            %ul
              %li.right_btn
                = link_to user_path(current_user),class: "right_btn" do
                  = image_tag("header-footer_images/member_photo.png", class: "member_photo left-float")
                  マイページ
              %li.right_btn
                = link_to class: "right_btn" do
                  %i.fa.fa-bell.icon
                  お知らせ
              %li.right_btn
                = link_to class: "right_btn" do
                  %i.fa.fa-check.icon
                  やることリスト
          -else
            %ul
              %ul.right_btn--signed-out
                %li.right_btn--signup
                  = link_to "新規会員登録", users_form_path,  class: 'top-signup-btn'
                %li.right_btn--login
                  = link_to "ログイン", new_user_session_path, class: 'top-login-btn'
              %ul.right_btn--signed-out

app/views/items/_item-box.html.haml
%li.item-box
  = link_to item_path(item) do
    = image_tag"#{item.item_images[0]&.image}", alt: ""
    -if item.order_status_id == 2
      .sold-out-box
        .sold-out-text SOLD
    .item-box-text
      .text-box
        %h4
        #{item.name}
      .price
        = number_to_currency(item.price, format:"%u%n", unit: "￥", strip_insignificant_zeros: true)
      .price-tax
        (税込)
      .nice
        = fa_icon "heart"
        %span
        #{item.likes.count}

app/views/items/_search_item-box.html.haml
%li.search_item-box
  = link_to item_path(item) do
    = image_tag"#{item.item_images[0]&.image}", alt: "", class: "search_image"
    -if item.order_status_id == 2
      .search_sold-out-box
        .search_sold-out-text SOLD
    .search_text
      .search_name
        #{item.name}
      .search_box
        .search_price
          = number_to_currency(item.price, format:"%u%n", unit: "￥", strip_insignificant_zeros: true)
        .search_price-tax
          (税込)
      .search_nice
        = fa_icon "heart"
        %span
        #{item.likes.count}
        

app/views/items/edit.html.haml
= render 'layouts/sellheader'
%main#main
  %section.container
    #sell__container
      %div
        .sell__container__inner
          %h2.sell__head 商品の情報を入力
          = form_for @item, class: "sell__form" do |f|
            .sell--upload__box
              %h3.sell--upload__head
                出品画像
                %span.form--require 必須
              %p 最大4枚までアップロードできます
              = f.fields_for :item_images do |fi|
                = fi.label :image, class: "sell--upload__drop__box" do
                  .sell--upload__drop__box__imageview
                    = fi.file_field :image,class:"file",style:"display:none;"
                    %pre
                      #preview
                        クリックしてファイルをアップロード
                    -unless fi.object.new_record?
                      .sell--upload__drop__box__preview
                        = image_tag ("#{fi.object.image}"), class: "uploadimg"
                        = fi.label :_destroy, class: "img_del" do
                          = fi.check_box :_destroy, {}, 1, 0
                          画像を削除する
            .sell__content
              .form__group
                %label
                  商品名
                  %span.form--require 必須
                %div
                  = f.text_field :name, class: "input__default", placeholder: "商品名（必須 40文字まで)"
              .form__group
                %label
                  商品の説明
                  %span.form--require 必須
                = f.text_area :description, class: "textarea__default", placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。", rows: "5"
            .sell__content.clearfix
              %h3.sell--sub__head 商品の詳細
              .sell__form__box
                .form__group
                  %label
                    カテゴリー
                    %span.form--require 必須
                  %div
                    #first-select
                      = f.select :first_category_id, options_from_collection_for_select(@first, :id, :first_category),{prompt: '---'}, {data: {remote: true, url: url_for(action: :secondcategory)}}
                    #second-select
                      = f.select :second_category_id, options_from_collection_for_select(SecondCategory.where(first_category_id: @item.first_category_id), :id, :second_category),{prompt: '---'}, {data: {remote: true, url: url_for(action: :thirdcategory)}}
                    #third-select
                      - if @item.third_category_id?
                        = f.select :third_category_id, options_from_collection_for_select(ThirdCategory.where(second_category_id: @item.second_category_id), :id, :third_category),{prompt: '---'}

                .form__group
                  %label
                    商品のサイズ
                    %span.form--require 必須
                  = f.collection_select :size_id, Size.all, :id, :size,{prompt: '---'}, class: "select__default"
                .form__group
                  %label
                    ブランド
                    %span 任意
                  = f.text_field :brand_id, class: "input__default"
                .form__group
                  %label
                    商品の状態
                    %span.form--require 必須
                  = f.collection_select :condition_id, Condition.all, :id, :condition,{prompt: '---'}, class: "select__default"
            .sell__content.clearfix
              %h3.sell--sub__head 配送について
              = link_to '?', "/jp/help_center/article/68/",class: "form__question"
              .sell__form__box
                .form__group
                  %label
                    配送料の負担
                    %span.form--require 必須
                  = f.collection_select :delivery_charge_id, DeliveryCharge.all, :id, :charge, {prompt: '---'},class: "select__default"
                .form__group
                  %label
                    配送方法
                    %span.form--require 必須
                  = f.collection_select :delivery_way_id, DeliveryWay.all, :id, :way, {prompt: '---'},class: "select__default"
                .form__group
                  %label
                    発送元の地域
                    %span.form--require 必須
                  = f.collection_select :prefecture_id, Prefecture.all, :id, :prefecture,{prompt: '---'}, class: "select__default"
                .form__group
                  %label
                    発送までの日数
                    %span.form--require 必須
                    = f.collection_select :delivery_date_id, DeliveryDate.all, :id, :date,{prompt: '---'}, class: "select__default"
            .sell__content.clearfix
              %h3.sell--sub__head 販売価格(300〜9,999,999)
              = link_to '?', "/jp/help_center/article/68/", class: "form__question"
              .sell__form__box
                %ul.sell__price
                  %li.form__group
                    .clearfix
                      %label.l-left
                        価格
                        %span.form--require 必須
                      .l-right.sell__price--input
                        ¥
                        %div#sellprice
                          =f.number_field :price, class: "input__default", id: "input__price", placeholder: "例）300", value: "#{@item.price}"
                  %li.clearfix
                    .l-left 販売手数料 (10%)
                    .l-right#output
                      = commission_jpy(@item.price * 0.1)
                  %li.clearfix.bold
                    .l-left 販売利益
                    .l-right#output2
                      = profit_jpy(@item.price * 0.9)
            = f.number_field :order_status_id, value: "1", type: "hidden"
            .sell__content.sell__btn__box
              %div
                %p
                  = link_to '禁止されている出品', "/jp/help_center/getting_started/prohibited_items/"
                  、
                  = link_to '行為を必ずご確認ください。', "/jp/help_center/getting_started/prohibited_conduct/"
                %p
                  またブランド品でシリアルナンバー等がある場合はご記載ください。
                  = link_to '偽ブランドの販売', "/jp/help_center/getting_started/counterfeit_goods/"
                  は犯罪であり処罰される可能性があります。
                %p
                  また、出品をもちまして
                  = link_to '加盟店規約', "/jp/seller_terms/"
                  に同意したことになります。
              %button.btn__default.btn--red{type: "submit"}
                編集する
              = link_to 'もどる', root_path, class: "btn--gray"
= render 'layouts/sellfooter'

app/views/items/search.html.haml
= render partial: "header"
.breads
  - breadcrumb :item_search
  = breadcrumbs separator: "#{content_tag(:i, '', class: 'fa fa-caret-right')}"
.default-container_search
  .large-content
    .large-content__head
      %h2
      検索結果
    .large-content__number
      #{@search_items.where.not(order_status_id: 3).count}件表示
    .large-content__item
      - @search_items.each do |item|
        -if item.order_status_id != 3
          = render partial: 'items/search_item-box', locals: {item:item}
      %end
  .left-side
    .left-side_title 詳細検索
    .left-side_search
      = search_form_for @search, url: search_path do |f|
        .left-side__box
          = f.label :キーワード検索
          = f.text_field :name_cont, placeholder:"入力してください"
        .left-side__box
          = f.label :カテゴリー検索
          = f.select :first_category_id_eq, options_from_collection_for_select( FirstCategory.all, :id, :first_category),{prompt: '選択してください'}, {data: {remote: true, url: url_for(action: :search_secondcategory)}}
          #search_second-select
          #search_third-select
        .left-side__box
          = f.label :ブランド検索
          = f.collection_select :brand_id_eq, Brand.all, :id, :brand,{prompt: '選択してください'}
        .left-side__box
          = f.label :サイズ指定
          = f.collection_select :size_id_eq, Size.all, :id, :size,{prompt: '選択してください'}
        .left-side__box-price
          = f.label :価格
          = f.text_field :price_gteq, placeholder:"￥ Min〜"
          = f.text_field :price_lteq, placeholder:"￥ 〜Max"
        .left-side__box-correct
          = f.label :商品の状態
          .left-side__box-correction
            .correction-list
              = f.radio_button :condition_id_eq, '', {checked: true} 
              すべて
            .correction-list
              = f.radio_button :condition_id_eq, 1 
              新品・未使用
            .correction-list
              = f.radio_button :condition_id_eq, 2 
              未使用に近い
            .correction-list
              = f.radio_button :condition_id_eq, 3 
              目立った傷や汚れなし
            .correction-list
              = f.radio_button :condition_id_eq, 4 
              やや傷や汚れあり
            .correction-list
              = f.radio_button :condition_id_eq, 5 
              傷やよごれあり
            .correction-list
              = f.radio_button :condition_id_eq, 6 
              全体に状態が悪い
        .left-side__box-correct2
          = f.label :配送料の負担
          .left-side__box-correction2
            .correction-list
              = f.radio_button :delivery_charge_id_eq, '', {checked: true} 
              すべて
            .correction-list
              = f.radio_button :delivery_charge_id_eq, 1 
              送料込み(出品者負担)
            .correction-list
              = f.radio_button :delivery_charge_id_eq, 2 
              着払い(購入者負担)
        .left-side__box-correct2
          = f.label :販売状況
          .left-side__box-correction2
            .correction-list
              = f.radio_button :order_status_id_eq, '', {checked: true} 
              すべて
            .correction-list
              = f.radio_button :order_status_id_eq, 1 
              販売中
            .correction-list
              = f.radio_button :order_status_id_eq, 2 
              売り切れ
        .left-side__box-submit
          = link_to 'リセット', request.path, class: :reset_button
          -# = f.submit "リセット", type: :input, class: :reset_button, request.path
          = f.submit "完了", class: :search_submit
        %end
          
= render partial: "footer"

app/views/items/search_secondcategory.js.haml
$('#search_second-select').html(
"#{j(select :q, :second_category_id_eq, options_from_collection_for_select(@secondcategory, :id, :second_category),{prompt: '---'}, {data: {remote: true, url: url_for(action: :search_thirdcategory)}})}"
);

app/views/items/search_thirdcategory.js.haml
$('#search_third-select').html(
"#{j(select :q, :third_category_id_eq, options_from_collection_for_select(@thirdcategory, :id, :third_category),{prompt: '---'})}"
);

app/views/items/secondcategory.js.erb
if($('#item_first_category_id').val() !== ""){
  $('#second-select').html(
    "<div><div class=select--wrap><%= j(select :item, :second_category_id, options_from_collection_for_select(@secondcategory, :id, :second_category),{prompt: '---'}, {data: {remote: true, url: url_for(action: :thirdcategory)}}) %></div></div>"
  );
}else{
  $('#second-select').html(
    ""
  );
}

$("#third-select").html("");

app/views/items/show.html.haml
= render partial: "header"
.breads
  - breadcrumb :item_show, @item
  = breadcrumbs separator: "#{content_tag(:i, '', class: 'fa fa-caret-right')}"
.default-container
  %section.item-container
    - @item.communications.each do |communication|
      - if  communication.user.expert_or_ordinary == true  &&  communication.user.third_category_id == @item.third_category_id
        .item-container__function
          .expart-function__blue
            .expart_button 専門家認定品
    %h1 #{@item.name}
    .item-container__main-content
    .item-container__image
      = image_tag "#{@item_images[0]&.image}", alt: "", id: "main-box"
      -if @item.order_status_id == 2
        .sold-out-box
          .sold-out-text SOLD
      %ul.image-slide
        - @item_images.each do|item|
          %li
            =image_tag "#{item.image}",alt:"", class: "slide-box"

    %table.item-container__detail
      %tbody
        %tr
          %th 出品者
          %td
            = link_to "#{@item.user.nickname}"
        %tr
          %th カテゴリー
          %td
            = link_to "#{@item.first_category.first_category}"
            %br
            = link_to "\> #{@item.second_category.second_category}"
            %br
            = link_to "\> #{@item.third_category.third_category}"
        %tr
          %th ブランド
          %td #{@item.brand&.brand}
        %tr
          %th 商品のサイズ
          %td #{@item.size&.size}
        %tr
          %th 商品の状態
          %td #{@item.condition.condition}
        %tr
          %th 配送料の負担
          %td #{@item.delivery_charge.charge}
        %tr
          %th 配送の方法
          %td #{@item.delivery_way.way}
        %tr
          %th 配送元地域
          %td
            = link_to "#{@item.prefecture.prefecture}"
        %tr
          %th 発送日の目安
          %td #{@item.delivery_date.date}
    .item-container__price
      %span.item-price
        = number_to_currency(@item.price, format:"%u%n", unit: "￥", strip_insignificant_zeros: true)
      %span.item-taxIn
        (税込)
      %span.item-tax-include
        \送料込み
      -if user_signed_in?
        -if @item.user_id != current_user.id
          -if @item.order_status_id == 1
            = link_to order_confirm_path(@item) do
              .order-status1 購入画面に進む
          -elsif @item.order_status_id == 2
            .order-status この商品は売却済です
        -else
          .no-text
      -else
        .order-status ログインしていないため購入できません
    .item-container__discription
      %p
      \#{@item.description}
    .item-container__function2
      -if user_signed_in?
        - if current_user.already_liked?(@item)
          .like-function__red
            %i.fas.fa-heart.faa-pulse.animated
            = link_to 'いいね！', item_like_path(@item), class: :like_button, method: :delete
            %span
              #{@item.likes.count}
        - else
          .like-function
            =  fa_icon "heart"
            = link_to 'いいね！', item_likes_path(@item) ,class: :like_button, method: :post
            %span
              #{@item.likes.count}

  - if user_signed_in?
    .comment
      .comment__box
        - @item.communications.each do |communication|
          .comment__box__communication
            .comment__box__communication__user-icon
              - if communication.user.user_icon.present?
                = image_tag communication.user.user_icon
              - else
                = image_tag "header-footer_images/member_photo.png"
                %br
                - if  communication.user.expert_or_ordinary == true  &&  communication.user.third_category_id == @item.third_category_id
                  %p(style="color: blue;")
                    専門家
                - elsif communication.seller_or_buyer == true && communication.item_id == @item.id
                  %p
                    出品者
                - else
            .comment__box__communication__message
              .comment__box__communication__message__name
                = communication.user.nickname
              .comment__box__communication__message__text.balloon
                = communication.message
      .comment__form
        %p相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
        = form_for [@item, @message] do |f|
          = f.text_field :message, placeholder: '',class: "form", value: ''
          = f.number_field :order_status_id, value: "#{@item.order_status_id}", type: "hidden"
          = f.number_field :user_id, value: "#{@user.id}", type: "hidden"
          - if @user.id == @item.user_id
            = f.number_field :seller_or_buyer, value: "1", type: "hidden"
          - else
            = f.number_field :seller_or_buyer, value: "", type: "hidden"
          = f.submit "コメントする", class: 'send'
  .sns-media
    %i.fab.fa-facebook-square
    %i.fab.fa-twitter-square
    %i.fab.fa-line
    %i.fab.fa-pinterest-square
  .other-item-box
    %h2
      = link_to "#{@item.user.nickname}さんのその他の商品", user_item_show_path(@item)
    .other-item-contents
      -@item.user.items.first(6).each do |item|
        .other-item-contents__box
          = link_to "#{item.id}" do
            .photo
              = image_tag "#{item.item_images[0].image}"
            .text
              %h3 #{item.name}
              .price-box
                .price
                  = number_to_currency(@item.price, format:"%u%n", unit: "￥", strip_insignificant_zeros: true)
                = fa_icon "heart"
                %span
                  #{item.likes.count}
                %p （税込）

  .other-item-box
    %h2
      = link_to "#{@item.third_category.third_category}(#{@item.first_category.first_category})のその他の商品", thirdcategory_path(@item)
    .other-item-contents
      - Item.where(third_category_id: @item.third_category.id).first(6).each do |item|
        .other-item-contents__box
          = link_to "#{item.id}" do
            .photo
              = image_tag "#{item.item_images[0].image}"
            .text
              %h3 #{item.name}
              .price-box
                .price
                  = number_to_currency(item.price, format:"%u%n", unit: "￥", strip_insignificant_zeros: true)
                = fa_icon "heart", class: :heart
                %span
                  #{item.likes.count}
                %p （税込）
      
= render partial: "footer"

app/views/items/thirdcategory.js.erb
if($("#item_second_category_id").val() !== "" ){
  $('#third-select').html(
    "<div><div class=select--wrap><%= j(select :item, :third_category_id, options_from_collection_for_select(@thirdcategory, :id, :third_category),{prompt: '---'}) %></div></div>"
  );
}else{
  $('#third-select').html(
    ""
  );
}